version: "3"

services:
  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=user
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
